In [1]:
import pandas as pd

In [4]:
path = "ventas.xlsx"

df_ventas = pd.read_excel(path)
display(df_ventas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venta        120 non-null    int64
 1   fecha           120 non-null    datetime64[ns]
 2   id_cliente      120 non-null    int64
 3   nombre_cliente  120 non-null    object
 4   email           120 non-null    object
 5   medio_pago      120 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 5.8+ KB

None

Obsevaciones: 
- Se tienen que eliminar columnas que no aporten datos de valor
  - id_venta (sirve para relacionarlo a las otras tablas)
  - id_cliente (seria dato personal y no es relevante)
  - nombre_cliente (mismo que arriba)
  - email (idem)
- La fecha ya esta en datetime, solo quedaria convertir el medio_pago en string

In [5]:
display(df_ventas.describe())

         id_venta                fecha  id_cliente
count  120.000000                  120  120.000000
mean    60.500000  2024-03-29 17:36:00   47.291667
min      1.000000  2024-01-02 00:00:00    1.000000
25%     30.750000  2024-02-11 06:00:00   24.500000
50%     60.500000  2024-03-25 00:00:00   48.500000
75%     90.250000  2024-05-19 06:00:00   67.500000
max    120.000000  2024-06-28 00:00:00  100.000000
std     34.785054                  NaN   27.854181

In [ ]:
df_clean = df_ventas.drop(columns=["id_venta", "id_cliente", "nombre_cliente", "email"])
df_clean["fecha"] = df_clean["fecha"].replace(" ","")
display(df_clean.describe())

                     fecha
count                  120
mean   2024-03-29 17:36:00
min    2024-01-02 00:00:00
25%    2024-02-11 06:00:00
50%    2024-03-25 00:00:00
75%    2024-05-19 06:00:00
max    2024-06-28 00:00:00

Agrego columnas para tener mas data asociada a fecha
- Mes
- Cuatrimestre
- Semana

In [8]:
df_clean["fecha"] = pd.to_datetime(df_clean['fecha'])
df_clean["mes"] = df_clean["fecha"].dt.to_period("M")

display(df_clean.describe(include="all"))

                      fecha medio_pago      mes
count                   120        120      120
unique                  NaN          4        6
top                     NaN   efectivo  2024-01
freq                    NaN         37       24
mean    2024-03-29 17:36:00        NaN      NaN
min     2024-01-02 00:00:00        NaN      NaN
25%     2024-02-11 06:00:00        NaN      NaN
50%     2024-03-25 00:00:00        NaN      NaN
75%     2024-05-19 06:00:00        NaN      NaN
max     2024-06-28 00:00:00        NaN      NaN

In [15]:
# Agrego cuatrimestre y trimestre
df_clean["cuatrimestre"] = ((df_clean["fecha"].dt.month - 1) // 4 + 1).astype(int)
df_clean["anio_cuatrimestre"] = df_clean["fecha"].dt.year.astype(str) + "-C" + df_clean["cuatrimestre"].astype(str)

display(df_clean.describe(include="all"))
display(df_clean)

,fecha,medio_pago,mes,cuatrimestre,anio_cuatrimestre,trimestre
count,120,120,120,120.000000,120,120.000000
unique,NaN,4,6,NaN,2,NaN
top,NaN,efectivo,2024-01,NaN,2024-C1,NaN
freq,NaN,37,24,NaN,77,NaN
mean,2024-03-29 17:36:00,NaN,NaN,1.358333,NaN,1.458333
min,2024-01-02 00:00:00,NaN,NaN,1.000000,NaN,1.000000
25%,2024-02-11 06:00:00,NaN,NaN,1.000000,NaN,1.000000
50%,2024-03-25 00:00:00,NaN,NaN,1.000000,NaN,1.000000
75%,2024-05-19 06:00:00,NaN,NaN,2.000000,NaN,2.000000
max,2024-06-28 00:00:00,NaN,NaN,2.000000,NaN,2.000000
std,NaN,NaN,NaN,0.481521,NaN,0.500350

,fecha,medio_pago,mes,cuatrimestre,anio_cuatrimestre,trimestre
0,2024-06-19,tarjeta,2024-06,2,2024-C2,2
1,2024-03-17,qr,2024-03,1,2024-C1,1
2,2024-01-13,tarjeta,2024-01,1,2024-C1,1
3,2024-02-27,transferencia,2024-02,1,2024-C1,1
4,2024-06-11,tarjeta,2024-06,2,2024-C2,2
...,...,...,...,...,...,...
115,2024-03-18,qr,2024-03,1,2024-C1,1
116,2024-03-14,tarjeta,2024-03,1,2024-C1,1
117,2024-02-09,efectivo,2024-02,1,2024-C1,1
118,2024-02-07,qr,2024-02,1,2024-C1,1
119,2024-04-21,tarjeta,2024-04,1,2024-C1,2

Ahora se haria lo mismo con los otros datasets 

- detalle_ventas
- productos 
- etc.